//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodFiesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderElement
    {
        public int Food { get; set; }
        public int Order { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<float> Discount { get; set; }
    
        public virtual Food Food1 { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
