//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodFiesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockUpdateRecord
    {
        public int Id { get; set; }
        public Nullable<int> Seller { get; set; }
        public Nullable<int> Updated_stock { get; set; }
        public Nullable<int> Updated_ingredient { get; set; }
        public Nullable<float> Quantity { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Seller Seller1 { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
