//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodFiesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockElement
    {
        public int Stock { get; set; }
        public int Ingredient { get; set; }
        public Nullable<float> Quantity { get; set; }
    
        public virtual Stock Stock1 { get; set; }
    }
}
